### ISSUE TITLE
Unhandled exception occured in onPacketSending(PacketEvent) for LockettePro

### ISSUE THREAD

**Issue by L4BORG** [connection-lost/LockettePro#50]
```
[17:33:15 ERROR]: [LockettePro] Unhandled exception occured in onPacketSending(PacketEvent) for LockettePro
com.comphenix.protocol.reflect.FieldAccessException: No field with type net.minecraft.server.v1_8_R3.NBTTagCompound exists in class PacketPlayOutUpdateSign.
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:219) ~[ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:198) ~[ProtocolLib.jar:4.3.0]
        at me.crafter.mc.lockettepro.DependencyProtocolLib$1.onPacketSending(DependencyProtocolLib.java:71) ~[LockettePro.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:386) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:352) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:320) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.3.0]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:192) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:141) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:911) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.EntityPlayer.a(EntityPlayer.java:571) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.EntityPlayer.t_(EntityPlayer.java:263) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1650) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.World.g(World.java:1617) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1450) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:600) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:846) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[17:33:15 ERROR]: Parameters:
  net.minecraft.server.v1_8_R3.PacketPlayOutUpdateSign@171eb2f3[
    a=net.minecraft.server.v1_8_R3.WorldServer@392e6b21
    b=BlockPosition{x=-44, y=112, z=76}
    c={TextComponent{text='', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}},TextComponent{text='', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}},TextComponent{text='', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}},TextComponent{text='', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}}
  ]

>
```

```
>ver
[17:34:02 INFO]: This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[17:34:02 INFO]: Checking version, please wait...
[17:34:03 INFO]: Error obtaining version information
>ver ProtocolLib
[17:34:06 INFO]: ProtocolLib version 4.3.0
[17:34:06 INFO]: Provides read/write access to the Minecraft protocol.
[17:34:06 INFO]: Authors: dmulloy2 and comphenix
>ver Lo
LogBlock      LockettePro
>ver LockettePro
[17:34:11 INFO]: LockettePro version 2.8.1
[17:34:11 INFO]: LockettePro is a chest protection plugin for Bukkit. It is 100% compatible with original Lockette, but delivers a lot of performance enhancements and feature options.

[17:34:11 INFO]: Author: connection_lost
>
```

**Comment by connection-lost** [comment]
Unfortunately, this is due to: https://github.com/aadnk/ProtocolLib/issues/137

**Comment by 502647092** [comment]
@L4BORG you can use this ProtocolLib verison http://ci.yumc.pw/job/ProtocolLib/

**Comment by L4BORG** [comment]
We need old version of protocollib because of viaversion :(

**Comment by L4BORG** [comment]
It seems like this is not an issue on old version of ProtocolLib tho
