### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LoociM00** [connection-lost/LockettePro#98]
Plugin seems to be working fine, however I get this error on start-up.

`25.02 18:57:28 [Server] INFO Enabling LockettePro v2.9.0
25.02 18:57:28 [Server] ERROR Error occurred while enabling LockettePro v2.9.0 (Is it up to date?)
25.02 18:57:28 [Server] INFO java.lang.NoClassDefFoundError: com/intellectualcrafters/plot/api/PlotAPI
25.02 18:57:28 [Server] INFO at me.crafter.mc.lockettepro.Dependency.<init>(Dependency.java:81) ~[?:?]
25.02 18:57:28 [Server] INFO at me.crafter.mc.lockettepro.LockettePro.onEnable(LockettePro.java:31) ~[?:?]
25.02 18:57:28 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot_latest.jar:git-Spigot-b0f4c22-2ced023]
25.02 18:57:28 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot_latest.jar:git-Spigot-b0f4c22-2ced023]
25.02 18:57:28 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot_latest.jar:git-Spigot-b0f4c22-2ced023]
25.02 18:57:28 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [spigot_latest.jar:git-Spigot-b0f4c22-2ced023]
25.02 18:57:28 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [spigot_latest.jar:git-Spigot-b0f4c22-2ced023]
25.02 18:57:28 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot_latest.jar:git-Spigot-b0f4c22-2ced023]
25.02 18:57:28 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot_latest.jar:git-Spigot-b0f4c22-2ced023]
25.02 18:57:28 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot_latest.jar:git-Spigot-b0f4c22-2ced023]
25.02 18:57:28 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot_latest.jar:git-Spigot-b0f4c22-2ced023]
25.02 18:57:28 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot_latest.jar:git-Spigot-b0f4c22-2ced023]
25.02 18:57:28 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]
25.02 18:57:28 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.intellectualcrafters.plot.api.PlotAPI
25.02 18:57:28 [Server] INFO at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_162]
25.02 18:57:28 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:134) ~[spigot_latest.jar:git-Spigot-b0f4c22-2ced023]
25.02 18:57:28 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:80) ~[spigot_latest.jar:git-Spigot-b0f4c22-2ced023]
25.02 18:57:28 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_162]
25.02 18:57:28 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_162]
25.02 18:57:28 [Server] INFO ... 13 more`

**Comment by BluGhostYT** [comment]
It is not yet released for 1.13.2

**Comment by VaneHD** [comment]
This isn't a problem on LockettePro's side. Its a plugin on your server that causes this error to occur.
